### ISSUE TITLE
Please finish

### ISSUE THREAD

**Issue by TacosYum** [Sandertv/RandomSpawn#1]
Please

**Comment by NycuRO** [comment]
@Sandertv Can you finish plugin? :)

**Comment by Sandertv** [comment]
I'll quickly code this right now... hang on.

**Comment by Sandertv** [comment]
Try installing the latest version. It is likely not to work yet, but please tell me if it throws an error once you do test it.

**Comment by NycuRO** [comment]
Ok :D

**Comment by NycuRO** [comment]
@Sandertv Can you modify command in "/rs" and add one configuration ?

Configuration for MAX "X" and MAX "Z".

Use this code:  

```for ($x =0; x<= 10000; ++$x) 
   {
      $teleport player bla bla 
}```

**Comment by Sandertv** [comment]
I might in the future. Question is though, does it work already?

**Comment by NycuRO** [comment]
I don't have time to test.. I'm working on Tesseract Generation now.

**Comment by NycuRO** [comment]
@Sandertv Hi , new update?
